### ISSUE TITLE
createDeviceUID is nowhere defined

### ISSUE THREAD

**Issue by InsOpDe** [nikeee/node-jodel-api#11]
the lib has no exported member 'createDeviceUID' as the example suggests

**Comment by nikeee** [comment]
Did you use the latest version on NPM or the one currently checked in in this repository?

The API changed, so the example in this repo do not apply to the current npm package.

**Comment by InsOpDe** [comment]
yes that was the problem, thank you

**Comment by nikeee** [comment]
I will soon publish a 2.0.0.
