### ISSUE TITLE
After npm install the folder in node_modules is empty

### ISSUE THREAD

**Issue by christophglass** [nikeee/node-jodel-api#14]
Hi,

after npm install -S jodel-api the folder "jodel-api" in node_modules only contains the following files:
- LICENSE
- package.json
- README.md

Thank you and best regards
Christoph

**Comment by nikeee** [comment]
Fixed in 5e944618a7f10b081f28b6f9e08911832b0db38c, released as 2.1.3!

Thanks for filing this issue!
