### ISSUE TITLE
Module not found errors

### ISSUE THREAD

**Issue by christophglass** [nikeee/node-jodel-api#15]
Hi,

I try to use your module in an Angular6 app. Installing runs fine now, but when I try to complie the project the following errors occur:

```
ERROR in ./node_modules/jodel-api/lib/crypto.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\jodel-api\lib'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\node-fetch'
ERROR in ./node_modules/node-fetch/lib/response.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\node-fetch\lib'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\node-fetch'
ERROR in ./node_modules/iconv-lite/lib/streams.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\iconv-lite\lib'
ERROR in ./node_modules/iconv-lite/lib/extend-node.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\iconv-lite\lib'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\node-fetch'
ERROR in ./node_modules/node-fetch/lib/body.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\node-fetch\lib'
ERROR in ./node_modules/node-fetch/index.js
Module not found: Error: Can't resolve 'zlib' in 'C:\Users\der-a\development\jodelmap\jodelmap\node_modules\node-fetch'
```

Any help is appreciated.

Thanks and best regards
Christoph

**Comment by nikeee** [comment]
Which version do you have installed?

Note that this Jodel-API currently only runs on Node.js. It uses some specific Node.js-APIs that are unavailable in the browser (stream, crypto).

If you want to use Angular, you'd have to use something like Electron to get a Nodejs environment.

**Comment by christophglass** [comment]
Hi,

I've got the latest version installed but at the moment it is even impossible to eject webpack.config from an angular-cli based to play around the issue. As you mentioned stream and crypto wont work, I'll have to look for another environment for developing my little jodel app.

Thanks and best regards
Christoph

**Comment by nikeee** [comment]
I think even if you polyfill these modules in a browser, there is still CORS which can cause problems. I don't know whether  their API is accessibl from other domains. If you find out, let me know.
