### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by flowl** [nikeee/node-jodel-api#16]
The example is not working; I placed version and key from the ojoc project but get this:

```
{ code: 477,
  text: 'unknown',
  content: '{"error":"Signed request expected","metadata":null}' }
```

**Comment by nikeee** [comment]
The ones from the ojoc project aren't that new either. The owner of ojoc was contacted by the jodel team and now does not provide the keys directly. You have to retrieve the keys yourself the way it is described in the ojoc docs.
See: https://bitbucket.org/cfib90/ojoc/issues/14/keep-up-with-hmac-key-changes

**Comment by nikeee** [comment]
I'll close this. If you have problems with a new key, feel free to re-open this issue.
