### ISSUE TITLE
Captcha solving?

### ISSUE THREAD

**Issue by nikeee** [nikeee/node-jodel-api#7]
Is there a captcha or something?
https://bitbucket.org/cfib90/ojoc/src/daee08edf493827916b3e15d11085d863ea8d65a/OJOC/Config.py?fileviewer=file-view-default

**Comment by ioncodes** [comment]
There are captchas, yes, look at my commit here: https://github.com/ioncodes/JodelAPI/commit/48e441247be9ab4c0b43f7608b514a3fda36f183
Solving the captcha will set verified = true
TL;DR:
To get the captcha: GET /user/verification/imageCaptcha?access_token={token}
remember the 'key'! Open the image (image_url), put the indices of the images containing raccoons (so starting from 0!) in an int[].
To solve the captcha: POST /user/verification/imageCaptcha?access_token={token}
{"key":"the key","answer":[the int[]]}
example:
{"key":"12121212","answer":[1,2,3,4]}
That will return wether it was successful or not.

**Comment by nikeee** [comment]
Okay, cool. I will implement this soon.
Thanks!

**Comment by nikeee** [comment]
According to [this](https://github.com/ioncodes/JodelAPI/issues/39), captchas were removed.
