### ISSUE TITLE
I get the error Signed request expected

### ISSUE THREAD

**Issue by Alexispap** [nikeee/node-jodel-api#9]
node .\ShowPosts.js
Loggin in...
Something failed:  { code: 477,
  text: 'unknown',
  content: 'Signed request expected' }

**Comment by nikeee** [comment]
Did you use the latest available key?

**Comment by Alexispap** [comment]
I'm not sure, what you mean by key, but i downloaded your code just some minutes ago

**Comment by Alexispap** [comment]
Ich seh grade, dass du vermutlich deutsch sprichst ;) Bin grade auf der Suche nach nem Programm, dass Jodelposts ausliest, die ich dann z.B. in ner Tabelle speichern kann. Geht das mit deinem Code? Oder hast du ne Ahnung, ob und wie das ginge?
Tausend Dank!

**Comment by nikeee** [comment]
Du brauchst einen Key (z. B. von hier: https://github.com/nikeee/node-jodel-api/blob/master/Keys.md). Den musst du zusammen mit der entsprechenden Versionsnummer vor dem Kompilieren mit tsc an die Stelle vom Sample-Code einsetzen.
Mit jedem Update der Jodel-App gibt es neue Schlüssel. Ein Schlüssel funktioniert nur eine bestimmte Zeit lang (d.h. User, die Ihre App nicht updaten, werden somit nach einer Zeit ausgeschlossen).

**Comment by nikeee** [comment]
Kannst du kurz bestätigen, ob es geht? Ich würde dann die Issue schließen.

**Comment by Alexispap** [comment]
Ja, hat funktioniert, aber nachdem ich mich mehrmals ein und ausgeloggt habe, stand nun error code 403 "forbidden" da. Weißt du woran das liegen könnte?

**Comment by nikeee** [comment]
Kann ich dir nicht genau sagen. Du solltest dir natürlich nicht immer einen neuen Account machen, sondern das Token wiederverwenden. Schau Mal hier: https://github.com/nikeee/jodel-printer

**Comment by Alexispap** [comment]
Habs geschafft, danke dir :)
